apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.secretName }}
stringData:
  # Variables d'environnement non-sensibles
  APP_ENV: {{ .Values.app.env.APP_ENV | quote }}
  APP_DEBUG: {{ .Values.app.env.APP_DEBUG | quote }}
  DB_CONNECTION: {{ .Values.app.env.DB_CONNECTION | quote }}
  DB_PORT: {{ .Values.app.env.DB_PORT | quote }}
  
  # Variables qui pointent vers la base de données MySQL
  # Le nom du service est construit par Helm. Par ex: "web-app-mysql"
  DB_HOST: {{ include "web-app.fullname" . }}-mysql

  # Variables qui viennent de la configuration de notre dépendance MySQL
  DB_DATABASE: {{ .Values.mysql.auth.database | quote }}
  DB_USERNAME: {{ .Values.mysql.auth.username | quote }}

  # Le mot de passe de la DB est stocké dans un autre Secret, créé par le chart MySQL.
  # On le récupère ici.
  DB_PASSWORD: {{ .Values.mysql.auth.password | quote }}

  # Pour la clé d'application, nous allons la générer aléatoirement.
  # C'est plus sécurisé que de la stocker.
  APP_KEY: "base64:{{ randAlphaNum 32 | b64enc }}"