# values.yaml for our web-app

# ------------------------------------
# Configuration de notre application
# ------------------------------------
app:
  image:
    repository: francky2001/t-clo
    tag: latest
    pullPolicy: IfNotPresent

  secretName: web-app-secrets

  env:
    APP_ENV: production
    APP_DEBUG: "false"
    DB_CONNECTION: mysql
    DB_PORT: "3306"
  resources:
  limits:
    cpu: 200m # Limite à 20% d'un CPU
    memory: 256Mi # Limite à 256 Mégaoctets de RAM
  requests:
    cpu: 100m # Demande 10% d'un CPU au démarrage
    memory: 128Mi # Demande 128 Mégaoctets de RAM au démarrage

replicaCount: 2

# ------------------------------------
# Configuration de la base de données MySQL
# ------------------------------------
mysql:
  enabled: true
  auth:
    database: "laravel_db"
    username: "laravel_user"
    password: ""
    rootPassword: ""
  primary:
    persistence:
      enabled: true
      storageClass: "local-path"
      size: 5Gi

# ------------------------------------
# Configuration du Service Kubernetes
# ------------------------------------
service:
  type: ClusterIP
  port: 80

# ------------------------------------
# Configuration du service account
# ------------------------------------
serviceAccount:
  create: false
  name: ""

# ------------------------------------
# Configuration de l'Autoscaling (HPA)
# ------------------------------------
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

# ------------------------------------
# Configuration de l'Ingress
# ------------------------------------
ingress:
  enabled: true # On active la création de l'Ingress
  className: "nginx" # On spécifie la classe d'ingress NGINX
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: webapp.kubequest.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: webapp-tls
      hosts:
        - webapp.kubequest.local
